driver:
  name: dokken

transport:
  name: dokken
  
provisioner:
  name: dokken
  log_level: info
  require_chef_omnibus: 12.19.36

platforms:
  - name: centos-7.2
    driver:
      image: centos:7.2.1511
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN /usr/bin/yum install -y sudo
suites:
  - name: default
    run_list:
        - recipe[overstat_elk::default]
    attributes:
