---
driver:
  name: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
        - recipe[overstat_elk::default]
    attributes:
